// The try statement allows you to define a block of code to be tested for errors while it is being executed.

// The throw keyword throws an exception when a problem is detected, which lets us create a custom error.

// The catch statement allows you to define a block of code to be executed, if an error occurs in the try block.

// The try and catch keywords come in pairs 
#include<iostream>
using namespace std;
int main(){
    try
    {
        if
    }
    catch(const std::exception& e)
    {
        std::cerr << e.what() << '\n';
    }
    

return 0;
}